name: flutterfire_plugins

packages:
  - packages/**

scripts:
  # Analyze the project for Dart analysis issues.
  #  - Requires `pub global activate tuneup`.
  analyze: >
    melos exec -c 1 --fail-fast -- \
      pub global run tuneup check

  # Formats the code of all packages (Java, Objective-C, and Dart).
  #   - Requires `git`.
  #   - Requires `clang-format` (can be installed via Brew on MacOS).
  format: pub global run flutter_plugin_tools format

  # Build iOS plugin example apps.
  build:examples:ios: >
    melos exec -c 1 --scope="*example*" --fail-fast -- \
      flutter build ios --no-codesign

  # Build iOS plugin example apps.
  build:examples:android: >
    melos exec -c 1 --scope="*example*" --fail-fast -- \
      flutter build apk

  # Build any plugin example apps that have MacOS support.
  # - Requires `flutter config --enable-macos-desktop` enabled.
  # - Requires `flutter channel master && flutter upgrade`.
  build:examples:macos: >
    melos exec -c 1 --scope="*example*" --dir-exists=macos --fail-fast -- \
      flutter build macos

  # Run any Android Java tests.
  #  - Currently none in FlutterFire.
  test:java: >
    melos exec -c 1 --dir-exists=android/app/src/test -- \
      cd android \&\& ./gradlew testDebugUnitTest --info

  # Check pubspecs are valid and publishable in each package.
  lint:pub: >
    melos exec -c 5 --no-private --ignore="*example*" -- \
      pub publish --dry-run

  # MacOS only. Ignores stub iOS podspecs in web federated plugins.
  lint:podspecs: >
    melos exec -c 1 --ignore="*web*" --fail-fast --file-exists=ios/\$MELOS_PACKAGE_NAME.podspec -- \
      pod lib lint ./ios/\$MELOS_PACKAGE_NAME.podspec \
        --allow-warnings \
        --fail-fast \
        --include-podspecs=\$MELOS_ROOT_PATH/packages/firebase_core/firebase_core/ios/firebase_core.podspec

  # Additionally cleanup lifecycle script, executed when `melos clean` is ran.
  postclean: >
    melos exec -- \
      rm -rf ./build ./android/.gradle ./ios/.symlinks ./ios/Pods ./android/.idea ./.idea

dev_dependencies:
  pedantic: ^1.8.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"