name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core

dev_dependencies:
  pedantic: ^1.8.0
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.4.3+1

flutter:
  uses-material-design: true
