name: firestore_example
description: Demonstrates how to use the firestore plugin.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core

dependency_overrides:
  cloud_firestore:
    path: ../
  cloud_firestore_platform_interface:
    path: ../../cloud_firestore_platform_interface
  cloud_firestore_web:
    path: ../../cloud_firestore_web
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../../firebase_core/firebase_core_web

dev_dependencies:
  pedantic: ^1.8.0
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.1

flutter:
  uses-material-design: true
