name: core

on:
  pull_request:
    paths:
      - "packages/firebase_core/**"
      - ".github/workflows/core.yml"
      - "analysis_options.yaml"
  push:
    branches:
      - master

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*firebase_core*"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: "Install Tools"
        run: |
          pub global activate tuneup
          pub global activate melos
          echo "::add-path::$HOME/.pub-cache/bin"
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Analyze"
        run: |
          melos exec -c 3 --scope="$FLUTTERFIRE_PLUGIN_SCOPE" -- \
            tuneup check

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: "Install Tools"
        run: |
          pub global activate melos
          curl -sL https://github.com/google/google-java-format/releases/download/google-java-format-1.3/google-java-format-1.3-all-deps.jar -o $HOME/google-java-format.jar
          echo "::add-path::$HOME/.pub-cache/bin"
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Dart"
        run: |
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE" -- \
            flutter format .
          ./.github/workflows/scripts/validate-formatting.sh
      - name: "Objective-C"
        if: ${{ success() || failure() }}
        run: |
          melos exec -c 3 --scope="$FLUTTERFIRE_PLUGIN_SCOPE" --ignore="*platform_interface*" --ignore="*web*" -- \
            find . -maxdepth 3 -name "*.h" -o -name "*.m" -print0 \| xargs -0 clang-format -i --style=Google --verbose
          ./.github/workflows/scripts/validate-formatting.sh
      - name: "Java"
        if: ${{ success() || failure() }}
        run: |
          melos exec -c 3 --scope="$FLUTTERFIRE_PLUGIN_SCOPE" --ignore="*platform_interface*" --ignore="*web*" -- \
            find . -maxdepth 12 -name "*.java" -print0 \| xargs -0 java -jar $HOME/google-java-format.jar --replace
          ./.github/workflows/scripts/validate-formatting.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: "Install Tools"
        run: |
          pub global activate melos
          echo "::add-path::$HOME/.pub-cache/bin"
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Flutter Test"
        run: |
          melos exec -c 1 ---scope="$FLUTTERFIRE_PLUGIN_SCOPE" --dir-exists=test --ignore="*example*" -- \
            flutter test