name: firebase_core

on:
  pull_request:
    paths:
      - "packages/firebase_core/**"
      - ".github/workflows/firebase_core.yaml"
  push:
    branches:
      - master

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*firebase_core*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*firebase_core_example*"

jobs:
  android:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: "Install Tools"
        run: |
          pub global activate melos
          echo "::add-path::$HOME/.pub-cache/bin"
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Build Example"
        run: |
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" -- \
            flutter build apk
      - name: Drive Example
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          profile: Nexus 6
          script: |
            melos exec -c 1 --fail-fast --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" --dir-exists=test_driver -- \
              flutter drive --no-pub --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart

  ios:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: "Install Tools"
        run: |
          pub global activate melos
          echo "::add-path::$HOME/.pub-cache/bin"
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Build Example"
        run: |
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" -- \
            flutter build ios --no-codesign
      - name: "Boot Simulator"
        run: xcrun simctl boot "iPhone 11"
      - name: "Drive Example"
        run: |
          melos exec -c 1 --fail-fast --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" --dir-exists=test_driver -- \
            flutter drive --no-pub --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v1
        with:
          # https://github.com/subosito/flutter-action/issues/37
          channel: "beta"
      - name: "Install Tools"
        run: |
          pub global activate melos
          flutter config --enable-web
          echo "::add-path::$HOME/.pub-cache/bin"
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Build Example"
        run: |
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" --dir-exists=web -- \
            flutter build web
      - name: "Drive Example"
        run: |
          melos clean && melos bootstrap
          chromedriver --port=4444 &
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" --dir-exists=web -- \
            flutter drive --release --no-pub --verbose-system-logs --browser-name=chrome --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart
